//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatisticsCalculator.Resx {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StatisticsCalculator.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Add.
        /// </summary>
        public static string AddButtonText {
            get {
                return ResourceManager.GetString("AddButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Base calculator.
        /// </summary>
        public static string BaseCalculatorLabel {
            get {
                return ResourceManager.GetString("BaseCalculatorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Between.
        /// </summary>
        public static string BetweenLabel {
            get {
                return ResourceManager.GetString("BetweenLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Calculate.
        /// </summary>
        public static string CalculateLabel {
            get {
                return ResourceManager.GetString("CalculateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Clean.
        /// </summary>
        public static string CleanButtonText {
            get {
                return ResourceManager.GetString("CleanButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sample is empty.
        /// </summary>
        public static string EmptySampleText {
            get {
                return ResourceManager.GetString("EmptySampleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Greater than.
        /// </summary>
        public static string GreaterThanLabel {
            get {
                return ResourceManager.GetString("GreaterThanLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Less than.
        /// </summary>
        public static string LessThanLabel {
            get {
                return ResourceManager.GetString("LessThanLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Mean.
        /// </summary>
        public static string MeanLabel {
            get {
                return ResourceManager.GetString("MeanLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Median.
        /// </summary>
        public static string MedianLabel {
            get {
                return ResourceManager.GetString("MedianLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Mode.
        /// </summary>
        public static string ModeLabel {
            get {
                return ResourceManager.GetString("ModeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a New item....
        /// </summary>
        public static string NewSampleItemPlaceholder {
            get {
                return ResourceManager.GetString("NewSampleItemPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Normal distribution.
        /// </summary>
        public static string NormalDistributionLabel {
            get {
                return ResourceManager.GetString("NormalDistributionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Percentage.
        /// </summary>
        public static string PercentageLabel {
            get {
                return ResourceManager.GetString("PercentageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Population standard deviation.
        /// </summary>
        public static string PopulationStandardDeviationLabel {
            get {
                return ResourceManager.GetString("PopulationStandardDeviationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Population variance.
        /// </summary>
        public static string PopulationVarianceLabel {
            get {
                return ResourceManager.GetString("PopulationVarianceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sample.
        /// </summary>
        public static string SampleLabel {
            get {
                return ResourceManager.GetString("SampleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sample standard deviation.
        /// </summary>
        public static string SampleStandardDeviationLabel {
            get {
                return ResourceManager.GetString("SampleStandardDeviationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sample variance.
        /// </summary>
        public static string SampleVarianceLabel {
            get {
                return ResourceManager.GetString("SampleVarianceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Statistics.
        /// </summary>
        public static string StatisticsTabLabel {
            get {
                return ResourceManager.GetString("StatisticsTabLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sum of items.
        /// </summary>
        public static string SumOfItemsLabel {
            get {
                return ResourceManager.GetString("SumOfItemsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sum of square of items.
        /// </summary>
        public static string SumOfSquareLabel {
            get {
                return ResourceManager.GetString("SumOfSquareLabel", resourceCulture);
            }
        }
    }
}
